services:
    Fusonic\MessengerMailerBundle\Middleware\AttachmentEmailMiddleware:
        arguments:
            $handler: '@messenger_mailer.attachment_handler'

    Fusonic\MessengerMailerBundle\EmailAttachmentHandler\FilesystemAttachmentHandler:
        arguments:
            $attachmentsDirectory: "%kernel.project_dir%/var/email-attachments"
